# Generated by Django 3.2.8 on 2021-10-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ask', models.CharField(max_length=255, verbose_name='вопрос')),
                ('text_answer', models.TextField(verbose_name='текст ответа на вопрос')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_title', models.CharField(max_length=100, verbose_name='Заголовок инфы')),
                ('info_text', models.TextField(verbose_name='Текст инфы')),
                ('info_image', models.FileField(blank=True, upload_to='infoimg/', verbose_name='картинка')),
            ],
            options={
                'verbose_name': 'Инфа о нас',
                'verbose_name_plural': 'Инфа о нас',
            },
        ),
        migrations.CreateModel(
            name='Marafon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marafon_name', models.CharField(max_length=255, verbose_name='Название марафона')),
                ('marafon_tiers', models.TextField(verbose_name='Описане марафона')),
                ('total_place', models.PositiveIntegerField(default=0, verbose_name='счетчик свободных мест')),
                ('marafon_desc', models.TextField(verbose_name='описание всего')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Стоимоть марафона')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'марафон',
                'verbose_name_plural': 'марафоны',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_sponsor', models.CharField(max_length=255, verbose_name='имя спонсора')),
                ('desc_sponsor', models.TextField(verbose_name='Описание спонсора')),
                ('url_image', models.FileField(blank=True, upload_to='sponsorimg/', verbose_name='УРЛ картинки')),
                ('link', models.TextField(verbose_name='линк на спонсора')),
            ],
            options={
                'verbose_name': 'спонсор',
                'verbose_name_plural': 'спонсоры',
            },
        ),
    ]
